### ISSUE TITLE
error decoding html entities

### ISSUE THREAD

**Issue by Suika** [miyachan/torako#8]
```
8.879Z WARN  torako::imageboard::model        > error decoding html entities (will do regex escaping): 'DecodeErr { position: 8, kind: PrematureEnd }':
'''
[b]Diet & Body Re-composition[/b]

Initial Body Fat and Body Composition Changes

General Philosophies of Muscle Mass Gain

[b]Sample Diets[/b]
Read the above articles, and decide whether you need to bulk (add muscle), cut (lose fat), or maintain.

Calculate your Total Daily Energy Expenditure (TDEE) in calories

<u>Bulking Diet:</u>
Calories: TDEE + 500 calories
Protein: 1+ grams per lb. bodyweight

<u>Cutting Diet:</u>
Calories: TDEE - 500 calories
Protein: 1.5+ grams per lb. bodyweight

<u>Maintenance:</u>
Calories: TDEE
Protein: 1.25+ grams per lb. bodyweight

Adjust calories as needed based on your goals / results.
'''

```

**Comment by miyachan** [comment]
This post specifically is a bit special; the 4chan API seems to misbeheaving here and returning invalid html entities. It does fallback to use regex escaping, which is the default in Asagi, so ultimately the post is stored as expected. For that reason I'm considering this working as intended.

The problem however is just the message - the warning is annoying, so I might disable it for just this post? I'd like to obviously catch any future issues, but every time you start Torako you hit this warning because of the sticked thread.
